# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'FirebaseUI'
pod 'Firebase/Storage'
pod 'MessageKit'
pod 'MessageInputBar'
# pod 'TwitterKit', '<3.3.0'
# pod 'TwitterCore', '<3.1.0'


# platform :ios, '8.0'

target 'Studor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Studor
  pod 'SendBirdSDK'
  
end

#  post_install do |installer|
#    installer.aggregate_targets.each do |aggregate_target|
#      aggregate_target.xcconfigs.each do |config_name, config_file|
#        config_file.other_linker_flags[:frameworks].delete("TwitterCore")
#
#        xcconfig_path = aggregate_target.xcconfig_path(config_name)
#        config_file.save_as(xcconfig_path)
#      end
#    end
#  end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
        end
    end
end
